import SalesSlideContainer from "@/components/sales-slides/SalesSlideContainer";
import { SlideNarrationProps } from "@/types/slideProps";
import { XCircle, CheckCircle } from "lucide-react";

interface Props extends SlideNarrationProps { slideNumber?: number; }

const beforeItems = [
  "Safety reports sit in one system",
  "Training delivered without context",
  "Content updated — no one notified",
  "Compliance proven manually",
  "Same events recur quarter after quarter",
];
const afterItems = [
  "Every signal triggers a connected response",
  "Training tied to the specific operational gap",
  "Content changes cascade automatically",
  "Compliance evidence generated by default",
  "Root causes closed — recurrence drops",
];
const metrics = [
  { label: "Investigation Time", value: "3 weeks → 3 days", sub: "85% faster" },
  { label: "Signal-to-Action", value: "40% → 95%", sub: "Every signal tracked" },
  { label: "Audit Readiness", value: "120hrs → 8hrs", sub: "Always audit-ready" },
];

const TechSlide3BeforeAfter = ({ slideNumber, ...narrationProps }: Props) => (
  <SalesSlideContainer id="tech-slide-3" title="Before & After" subtitle="From fragmented event management to connected operational performance" slideNumber={slideNumber} {...narrationProps}>
    <div className="flex-1 flex flex-col gap-4">
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        <div className="p-4 rounded-xl border border-red-500/20 bg-red-500/5">
          <div className="flex items-center gap-2 mb-3"><XCircle className="h-5 w-5 text-red-400" /><h3 className="text-lg font-bold text-red-400">Today: Fragmented</h3></div>
          <ul className="space-y-2">{beforeItems.map((i) => (<li key={i} className="flex items-start gap-2 text-sm text-muted-foreground"><span className="w-1.5 h-1.5 rounded-full bg-red-400/60 mt-1.5 shrink-0" />{i}</li>))}</ul>
        </div>
        <div className="p-4 rounded-xl border border-emerald-500/20 bg-emerald-500/5">
          <div className="flex items-center gap-2 mb-3"><CheckCircle className="h-5 w-5 text-emerald-400" /><h3 className="text-lg font-bold text-emerald-400">Connected: DTOP</h3></div>
          <ul className="space-y-2">{afterItems.map((i) => (<li key={i} className="flex items-start gap-2 text-sm text-muted-foreground"><span className="w-1.5 h-1.5 rounded-full bg-emerald-400/60 mt-1.5 shrink-0" />{i}</li>))}</ul>
        </div>
      </div>
      <div className="grid grid-cols-3 gap-3">
        {metrics.map((m) => (
          <div key={m.label} className="p-3 rounded-lg border border-primary/20 bg-primary/5 text-center">
            <span className="text-xs text-muted-foreground">{m.label}</span>
            <div className="text-lg font-bold text-foreground mt-1">{m.value}</div>
            <span className="text-xs text-primary">{m.sub}</span>
          </div>
        ))}
      </div>
    </div>
  </SalesSlideContainer>
);

export default TechSlide3BeforeAfter;
