import { X, Check, ArrowRight, AlertCircle, CheckCircle2, Database, TrendingUp } from "lucide-react";
import SalesSlideContainer from "./SalesSlideContainer";
import type { SlideNarrationProps } from "@/types/slideProps";

const beforeItems = [
  "Safety, content, training disconnected",
  "Investigations happen manually",
  "Training not tied to signals",
  "Evidence assembled late",
];

const afterItems = [
  "Detect → Trigger → Orchestrate → Prove",
  "Connected operating model",
  "Signals drive execution",
  "Proof generated by default",
];

const metrics = [
  { label: "OTP", value: "+3.2%", sublabel: "improvement" },
  { label: "Ready", value: "94%", sublabel: "workforce" },
  { label: "Audit", value: "2hr", sublabel: "vs months" },
];

// Particle generator for visual effect
const generateParticles = (count: number, scattered: boolean) => {
  const particles = [];
  for (let i = 0; i < count; i++) {
    const angle = (i / count) * Math.PI * 2;
    const radius = scattered ? 12 + Math.random() * 10 : 6 + Math.random() * 4;
    const x = Math.cos(angle) * radius;
    const y = Math.sin(angle) * radius;
    particles.push({ x, y, delay: i * 0.1 });
  }
  return particles;
};

interface SalesSlide3BeforeAfterProps extends SlideNarrationProps {
  slideNumber?: number;
}

const SalesSlide3BeforeAfter = ({
  slideNumber,
  isPlaying,
  isLoading,
  progress,
  hasCompleted,
  onPlay,
  onPause,
  onNextSlide,
}: SalesSlide3BeforeAfterProps) => {
  return (
    <SalesSlideContainer
      id="sales-slide-3"
      title="From Reactive to Predictable Operations"
      slideNumber={slideNumber}
      isPlaying={isPlaying}
      isLoading={isLoading}
      progress={progress}
      hasCompleted={hasCompleted}
      onPlay={onPlay}
      onPause={onPause}
      onNextSlide={onNextSlide}
    >
      <div className="flex-1 flex flex-col justify-center gap-4">
        {/* Before/After comparison with SVG visuals */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 max-w-5xl mx-auto">
          {/* Before */}
          <div className="bg-destructive/5 border border-destructive/20 rounded-xl p-5">
            <div className="flex items-center gap-2 mb-4">
              <div className="w-8 h-8 rounded-full bg-destructive/20 flex items-center justify-center">
                <AlertCircle className="w-4 h-4 text-destructive" />
              </div>
              <div>
                <h3 className="text-lg font-semibold text-destructive">Before</h3>
                <span className="text-xs text-muted-foreground">Fragmented Silos</span>
              </div>
            </div>

            {/* Data Fragmentation SVG */}
            <div className="h-28 mb-3">
              <svg viewBox="0 0 280 100" className="w-full h-full">
                {/* Broken connection lines */}
                <line x1="70" y1="40" x2="95" y2="40" stroke="hsl(var(--destructive))" strokeWidth="2" strokeDasharray="4 4" opacity="0.5" />
                <text x="82" y="38" fill="hsl(var(--destructive))" fontSize="10" fontWeight="bold">✕</text>
                <line x1="185" y1="40" x2="210" y2="40" stroke="hsl(var(--destructive))" strokeWidth="2" strokeDasharray="4 4" opacity="0.5" />
                <text x="197" y="38" fill="hsl(var(--destructive))" fontSize="10" fontWeight="bold">✕</text>

                {/* Safety Silo */}
                <circle cx="45" cy="40" r="28" fill="hsl(var(--destructive) / 0.1)" stroke="hsl(var(--destructive))" strokeWidth="2" opacity="0.7" />
                {generateParticles(6, true).map((p, i) => (
                  <circle key={`s-${i}`} cx={45 + p.x} cy={40 + p.y} r="2" fill="hsl(var(--destructive))" opacity="0.6" />
                ))}
                <text x="45" y="40" textAnchor="middle" dominantBaseline="middle" fill="hsl(var(--destructive))" fontSize="8" fontWeight="600">Safety</text>

                {/* Content Silo */}
                <circle cx="140" cy="40" r="28" fill="hsl(var(--destructive) / 0.1)" stroke="hsl(var(--destructive))" strokeWidth="2" opacity="0.7" />
                {generateParticles(8, true).map((p, i) => (
                  <circle key={`c-${i}`} cx={140 + p.x} cy={40 + p.y} r="2" fill="hsl(var(--destructive))" opacity="0.6" />
                ))}
                <text x="140" y="40" textAnchor="middle" dominantBaseline="middle" fill="hsl(var(--destructive))" fontSize="8" fontWeight="600">Content</text>

                {/* Training Silo */}
                <circle cx="235" cy="40" r="28" fill="hsl(var(--destructive) / 0.1)" stroke="hsl(var(--destructive))" strokeWidth="2" opacity="0.7" />
                {generateParticles(7, true).map((p, i) => (
                  <circle key={`t-${i}`} cx={235 + p.x} cy={40 + p.y} r="2" fill="hsl(var(--destructive))" opacity="0.6" />
                ))}
                <text x="235" y="40" textAnchor="middle" dominantBaseline="middle" fill="hsl(var(--destructive))" fontSize="8" fontWeight="600">Training</text>

                {/* Data volume labels */}
                <text x="45" y="78" textAnchor="middle" fill="hsl(var(--destructive))" fontSize="10" fontWeight="bold">12K</text>
                <text x="45" y="90" textAnchor="middle" fill="hsl(var(--muted-foreground))" fontSize="7">scattered</text>
                <text x="140" y="78" textAnchor="middle" fill="hsl(var(--destructive))" fontSize="10" fontWeight="bold">8K</text>
                <text x="140" y="90" textAnchor="middle" fill="hsl(var(--muted-foreground))" fontSize="7">orphaned</text>
                <text x="235" y="78" textAnchor="middle" fill="hsl(var(--destructive))" fontSize="10" fontWeight="bold">45K</text>
                <text x="235" y="90" textAnchor="middle" fill="hsl(var(--muted-foreground))" fontSize="7">manual</text>
              </svg>
            </div>

            <ul className="space-y-1.5">
              {beforeItems.map((item, index) => (
                <li key={index} className="flex items-start gap-2 text-xs text-muted-foreground">
                  <X className="w-3 h-3 text-destructive mt-0.5 shrink-0" />
                  {item}
                </li>
              ))}
            </ul>

            <div className="mt-3 p-2 bg-destructive/10 rounded-lg border border-destructive/20">
              <div className="flex items-center gap-1.5 mb-0.5">
                <Database className="w-3 h-3 text-destructive" />
                <span className="text-[10px] font-semibold text-destructive uppercase">Data Locked</span>
              </div>
              <p className="text-[10px] text-muted-foreground">65K+ data points trapped in silos</p>
            </div>
          </div>

          {/* After */}
          <div className="bg-emerald-500/5 border border-emerald-500/20 rounded-xl p-5">
            <div className="flex items-center gap-2 mb-4">
              <div className="w-8 h-8 rounded-full bg-emerald-500/20 flex items-center justify-center">
                <CheckCircle2 className="w-4 h-4 text-emerald-500" />
              </div>
              <div>
                <h3 className="text-lg font-semibold text-emerald-500">After</h3>
                <span className="text-xs text-muted-foreground">Predictable Performance</span>
              </div>
            </div>

            {/* Connected data SVG */}
            <div className="h-28 mb-3">
              <svg viewBox="0 0 280 100" className="w-full h-full">
                <defs>
                  <linearGradient id="connectionGrad" x1="0%" y1="0%" x2="100%" y2="0%">
                    <stop offset="0%" stopColor="hsl(var(--primary))" />
                    <stop offset="100%" stopColor="hsl(160 70% 45%)" />
                  </linearGradient>
                </defs>

                {/* Connection paths */}
                <path d="M 70 40 Q 105 25 140 40" fill="none" stroke="url(#connectionGrad)" strokeWidth="2.5" />
                <path d="M 140 40 Q 175 55 210 40" fill="none" stroke="url(#connectionGrad)" strokeWidth="2.5" />

                {/* Unified loop */}
                <path d="M 230 28 Q 260 40 230 52 Q 190 70 140 70 Q 90 70 50 52 Q 20 40 50 28 Q 90 10 140 10 Q 190 10 230 28"
                      fill="none" stroke="hsl(var(--primary))" strokeWidth="1.5" opacity="0.3" />

                {/* Safety circle - connected */}
                <circle cx="45" cy="40" r="26" fill="hsl(var(--primary) / 0.15)" stroke="hsl(var(--primary))" strokeWidth="2" />
                {generateParticles(6, false).map((p, i) => (
                  <circle key={`as-${i}`} cx={45 + p.x} cy={40 + p.y} r="2" fill="hsl(var(--primary))" opacity="0.8" />
                ))}
                <text x="45" y="40" textAnchor="middle" dominantBaseline="middle" fill="hsl(var(--primary))" fontSize="8" fontWeight="600">Safety</text>

                {/* Content circle - connected */}
                <circle cx="140" cy="40" r="26" fill="hsl(var(--primary) / 0.15)" stroke="hsl(var(--primary))" strokeWidth="2" />
                {generateParticles(8, false).map((p, i) => (
                  <circle key={`ac-${i}`} cx={140 + p.x} cy={40 + p.y} r="2" fill="hsl(var(--primary))" opacity="0.8" />
                ))}
                <text x="140" y="40" textAnchor="middle" dominantBaseline="middle" fill="hsl(var(--primary))" fontSize="8" fontWeight="600">Content</text>

                {/* Training circle - connected */}
                <circle cx="235" cy="40" r="26" fill="hsl(var(--primary) / 0.15)" stroke="hsl(var(--primary))" strokeWidth="2" />
                {generateParticles(7, false).map((p, i) => (
                  <circle key={`at-${i}`} cx={235 + p.x} cy={40 + p.y} r="2" fill="hsl(var(--primary))" opacity="0.8" />
                ))}
                <text x="140" y="40" textAnchor="middle" dominantBaseline="middle" fill="hsl(var(--primary))" fontSize="8" fontWeight="600">Content</text>
                <text x="235" y="40" textAnchor="middle" dominantBaseline="middle" fill="hsl(var(--primary))" fontSize="8" fontWeight="600">Training</text>

                {/* Central unified indicator */}
                <rect x="95" y="80" width="90" height="18" rx="4" fill="hsl(var(--primary) / 0.2)" stroke="hsl(var(--primary))" strokeWidth="1" />
                <text x="140" y="91" textAnchor="middle" dominantBaseline="middle" fill="hsl(var(--primary))" fontSize="8" fontWeight="600">65K+ Connected</text>
              </svg>
            </div>

            <ul className="space-y-1.5">
              {afterItems.map((item, index) => (
                <li key={index} className="flex items-start gap-2 text-xs text-foreground">
                  <Check className="w-3 h-3 text-emerald-500 mt-0.5 shrink-0" />
                  {item}
                </li>
              ))}
            </ul>

            <div className="mt-3 p-2 bg-primary/10 rounded-lg border border-primary/20">
              <div className="flex items-center gap-1.5 mb-1">
                <TrendingUp className="w-3 h-3 text-primary" />
                <span className="text-[10px] font-semibold text-primary uppercase">Value Generated</span>
              </div>
              <div className="grid grid-cols-3 gap-2 text-center">
                {metrics.map((m) => (
                  <div key={m.label}>
                    <p className="text-sm font-bold text-primary">{m.value}</p>
                    <p className="text-[9px] text-muted-foreground">{m.label}</p>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>

        {/* Unlike callout */}
        <div className="max-w-4xl mx-auto w-full">
          <div className="bg-card border border-primary/30 rounded-xl p-4">
            <p className="text-sm text-muted-foreground text-center">
              <span className="font-semibold text-primary">Unlike</span> point solutions that manage safety, content, or training in isolation,
              Comply365 connects all three — turning signals into <span className="text-primary font-semibold">orchestrated change</span> and <span className="text-primary font-semibold">audit-ready proof</span>.
            </p>
          </div>
        </div>
      </div>
    </SalesSlideContainer>
  );
};

export default SalesSlide3BeforeAfter;
