import SlideContainer from "./SlideContainer";
import { AlertCircle, CheckCircle2, Database, FileText, Users, TrendingUp, Clock, Shield } from "lucide-react";
import type { SlideNarrationProps } from "@/types/slideProps";

const Slide2BeforeAfter = ({
  isPlaying = false,
  isLoading = false,
  progress = 0,
  hasCompleted = false,
  onPlay,
  onPause,
  onNextSlide,
}: SlideNarrationProps) => {
  const beforeItems = [
    "Safety, procedures, training are disconnected",
    "Investigations and changes happen manually",
    "Training not tied to operational signals",
    "Evidence assembled late and inconsistently",
  ];

  const afterItems = [
    "Detect → Trigger → Orchestrate → Prove",
    "Connected operating model",
    "Signals drive controlled execution",
    "Proof generated by default",
  ];

  // Data particles for visual effect
  const generateParticles = (count: number, scattered: boolean) => {
    const particles = [];
    for (let i = 0; i < count; i++) {
      const angle = (i / count) * Math.PI * 2;
      const radius = scattered ? 15 + Math.random() * 12 : 8 + Math.random() * 5;
      const x = Math.cos(angle) * radius;
      const y = Math.sin(angle) * radius;
      particles.push({ x, y, delay: i * 0.1 });
    }
    return particles;
  };

  return (
    <SlideContainer
      id="slide-2"
      title="Before & After"
      subtitle="The operational reality we're transforming"
      slideNumber={2}
      isPlaying={isPlaying}
      isLoading={isLoading}
      progress={progress}
      hasCompleted={hasCompleted}
      onPlay={onPlay}
      onPause={onPause}
      onNextSlide={onNextSlide}
    >
      <div className="grid md:grid-cols-2 gap-6 lg:gap-10">
        {/* Before */}
        <div className="relative">
          <div className="relative bg-card border border-destructive/30 rounded-xl p-6 sm:p-8">
            <div className="flex items-center gap-3 mb-6">
              <div className="w-10 h-10 rounded-lg bg-destructive/20 flex items-center justify-center">
                <AlertCircle className="w-5 h-5 text-destructive" />
              </div>
              <div>
                <h3 className="text-xl font-bold text-destructive">Before</h3>
                <span className="text-xs text-muted-foreground">Fragmented Data Silos</span>
              </div>
            </div>

            {/* Data Fragmentation Visual */}
            <div className="relative h-48 mb-6">
              <svg viewBox="0 0 300 140" className="w-full h-full">
                <defs>
                  <filter id="siloGlow" x="-50%" y="-50%" width="200%" height="200%">
                    <feGaussianBlur stdDeviation="2" result="blur" />
                    <feMerge>
                      <feMergeNode in="blur" />
                      <feMergeNode in="SourceGraphic" />
                    </feMerge>
                  </filter>
                </defs>
                
                {/* Broken connection lines */}
                <line x1="80" y1="55" x2="105" y2="55" stroke="hsl(var(--destructive))" strokeWidth="2" strokeDasharray="4 4" opacity="0.4" />
                <text x="95" y="52" fill="hsl(var(--destructive))" fontSize="10" fontWeight="bold">✕</text>
                <line x1="195" y1="55" x2="220" y2="55" stroke="hsl(var(--destructive))" strokeWidth="2" strokeDasharray="4 4" opacity="0.4" />
                <text x="210" y="52" fill="hsl(var(--destructive))" fontSize="10" fontWeight="bold">✕</text>
                
                {/* Safety Silo */}
                <g>
                  <circle cx="55" cy="55" r="35" fill="none" stroke="hsl(var(--destructive))" strokeWidth="2" opacity="0.6" />
                  <circle cx="55" cy="55" r="28" fill="hsl(var(--destructive) / 0.1)" />
                  {/* Scattered data particles */}
                  {generateParticles(8, true).map((p, i) => (
                    <circle key={`s-${i}`} cx={55 + p.x} cy={55 + p.y} r="2" fill="hsl(var(--destructive))" opacity="0.6" />
                  ))}
                  <text x="55" y="52" textAnchor="middle" dominantBaseline="middle" fill="hsl(var(--destructive))" fontSize="9" fontWeight="600">Safety</text>
                  <text x="55" y="63" textAnchor="middle" fill="hsl(var(--destructive))" fontSize="7" opacity="0.8">Events</text>
                </g>
                
                {/* Procedures Silo */}
                <g>
                  <circle cx="150" cy="55" r="35" fill="none" stroke="hsl(var(--destructive))" strokeWidth="2" opacity="0.6" />
                  <circle cx="150" cy="55" r="28" fill="hsl(var(--destructive) / 0.1)" />
                  {generateParticles(10, true).map((p, i) => (
                    <circle key={`p-${i}`} cx={150 + p.x} cy={55 + p.y} r="2" fill="hsl(var(--destructive))" opacity="0.6" />
                  ))}
                  <text x="150" y="52" textAnchor="middle" dominantBaseline="middle" fill="hsl(var(--destructive))" fontSize="9" fontWeight="600">Procedures</text>
                  <text x="150" y="63" textAnchor="middle" fill="hsl(var(--destructive))" fontSize="7" opacity="0.8">Docs</text>
                </g>
                
                {/* Training Silo */}
                <g>
                  <circle cx="245" cy="55" r="35" fill="none" stroke="hsl(var(--destructive))" strokeWidth="2" opacity="0.6" />
                  <circle cx="245" cy="55" r="28" fill="hsl(var(--destructive) / 0.1)" />
                  {generateParticles(12, true).map((p, i) => (
                    <circle key={`t-${i}`} cx={245 + p.x} cy={55 + p.y} r="2" fill="hsl(var(--destructive))" opacity="0.6" />
                  ))}
                  <text x="245" y="52" textAnchor="middle" dominantBaseline="middle" fill="hsl(var(--destructive))" fontSize="9" fontWeight="600">Training</text>
                  <text x="245" y="63" textAnchor="middle" fill="hsl(var(--destructive))" fontSize="7" opacity="0.8">Records</text>
                </g>

                {/* Data volume labels */}
                <g>
                  <text x="55" y="105" textAnchor="middle" fill="hsl(var(--destructive))" fontSize="11" fontWeight="bold">12K</text>
                  <text x="55" y="118" textAnchor="middle" fill="hsl(var(--muted-foreground))" fontSize="8">scattered</text>
                  
                  <text x="150" y="105" textAnchor="middle" fill="hsl(var(--destructive))" fontSize="11" fontWeight="bold">8K</text>
                  <text x="150" y="118" textAnchor="middle" fill="hsl(var(--muted-foreground))" fontSize="8">orphaned</text>
                  
                  <text x="245" y="105" textAnchor="middle" fill="hsl(var(--destructive))" fontSize="11" fontWeight="bold">45K</text>
                  <text x="245" y="118" textAnchor="middle" fill="hsl(var(--muted-foreground))" fontSize="8">stale</text>
                </g>
              </svg>
            </div>

            <ul className="space-y-2">
              {beforeItems.map((item, index) => (
                <li key={index} className="flex items-start gap-3 text-sm text-muted-foreground">
                  <span className="w-1.5 h-1.5 rounded-full bg-destructive mt-2 shrink-0" />
                  {item}
                </li>
              ))}
            </ul>

            <div className="mt-4 p-3 bg-destructive/10 rounded-lg border border-destructive/20">
              <div className="flex items-center gap-2 mb-1">
                <Database className="w-4 h-4 text-destructive" />
                <span className="text-xs font-semibold text-destructive uppercase">Data Locked</span>
              </div>
              <p className="text-xs text-muted-foreground">
                65K+ data points trapped in silos, insights unavailable
              </p>
            </div>
          </div>
        </div>

        {/* After */}
        <div className="relative">
          <div className="relative bg-card border border-primary/30 rounded-xl p-6 sm:p-8">
            <div className="flex items-center gap-3 mb-6">
              <div className="w-10 h-10 rounded-lg bg-primary/20 flex items-center justify-center">
                <CheckCircle2 className="w-5 h-5 text-primary" />
              </div>
              <div>
                <h3 className="text-xl font-bold text-primary">After</h3>
                <span className="text-xs text-muted-foreground">Operational Excellence & Readiness Platform</span>
              </div>
            </div>

            {/* Connected data visual with flow */}
            <div className="relative h-48 mb-6">
              <svg viewBox="0 0 300 140" className="w-full h-full">
                <defs>
                  <linearGradient id="connectionGrad2" x1="0%" y1="0%" x2="100%" y2="0%">
                    <stop offset="0%" stopColor="hsl(var(--primary))" />
                    <stop offset="100%" stopColor="hsl(160 70% 45%)" />
                  </linearGradient>
                  <filter id="glowFilter" x="-50%" y="-50%" width="200%" height="200%">
                    <feGaussianBlur stdDeviation="3" result="blur" />
                    <feMerge>
                      <feMergeNode in="blur" />
                      <feMergeNode in="SourceGraphic" />
                    </feMerge>
                  </filter>
                </defs>
                
                {/* Connection paths with flow effect */}
                <path d="M 80 50 Q 115 30 150 50" fill="none" stroke="url(#connectionGrad2)" strokeWidth="3" />
                <path d="M 150 50 Q 185 70 220 50" fill="none" stroke="url(#connectionGrad2)" strokeWidth="3" />
                
                {/* Unified loop */}
                <path d="M 245 35 Q 280 50 245 65 Q 200 85 150 85 Q 100 85 55 65 Q 20 50 55 35 Q 100 15 150 15 Q 200 15 245 35" 
                      fill="none" stroke="hsl(var(--primary))" strokeWidth="1.5" opacity="0.3" />
                
                {/* Safety circle - connected */}
                <g>
                  <circle cx="55" cy="50" r="32" fill="hsl(var(--primary) / 0.15)" stroke="hsl(var(--primary))" strokeWidth="2" />
                  {generateParticles(8, false).map((p, i) => (
                    <circle key={`as-${i}`} cx={55 + p.x} cy={50 + p.y} r="2.5" fill="hsl(var(--primary))" opacity="0.8" />
                  ))}
                  <text x="55" y="50" textAnchor="middle" dominantBaseline="middle" fill="hsl(var(--primary))" fontSize="9" fontWeight="600">Safety</text>
                </g>
                
                {/* Procedures circle - connected */}
                <g>
                  <circle cx="150" cy="50" r="32" fill="hsl(var(--primary) / 0.15)" stroke="hsl(var(--primary))" strokeWidth="2" />
                  {generateParticles(10, false).map((p, i) => (
                    <circle key={`ap-${i}`} cx={150 + p.x} cy={50 + p.y} r="2.5" fill="hsl(var(--primary))" opacity="0.8" />
                  ))}
                  <text x="150" y="50" textAnchor="middle" dominantBaseline="middle" fill="hsl(var(--primary))" fontSize="9" fontWeight="600">Procedures</text>
                </g>
                
                {/* Training circle - connected */}
                <g>
                  <circle cx="245" cy="50" r="32" fill="hsl(var(--primary) / 0.15)" stroke="hsl(var(--primary))" strokeWidth="2" />
                  {generateParticles(12, false).map((p, i) => (
                    <circle key={`at-${i}`} cx={245 + p.x} cy={50 + p.y} r="2.5" fill="hsl(var(--primary))" opacity="0.8" />
                  ))}
                  <text x="245" y="50" textAnchor="middle" dominantBaseline="middle" fill="hsl(var(--primary))" fontSize="9" fontWeight="600">Training</text>
                </g>

                {/* Central unified data indicator */}
                <g transform="translate(150, 110)">
                  <rect x="-45" y="-12" width="90" height="24" rx="4" fill="hsl(var(--primary) / 0.2)" stroke="hsl(var(--primary))" strokeWidth="1" />
                  <text x="0" y="0" textAnchor="middle" dominantBaseline="middle" fill="hsl(var(--primary))" fontSize="9" fontWeight="600">65K+ Connected</text>
                </g>
              </svg>
            </div>

            <ul className="space-y-2">
              {afterItems.map((item, index) => (
                <li key={index} className="flex items-start gap-3 text-sm text-foreground">
                  <CheckCircle2 className="w-4 h-4 text-primary mt-0.5 shrink-0" />
                  {item}
                </li>
              ))}
            </ul>

            {/* Value Output Panel */}
            <div className="mt-4 p-3 bg-primary/10 rounded-lg border border-primary/20">
              <div className="flex items-center gap-2 mb-2">
                <TrendingUp className="w-4 h-4 text-primary" />
                <span className="text-xs font-semibold text-primary uppercase">Value Generated</span>
              </div>
              <div className="grid grid-cols-3 gap-2 text-center">
                <div>
                  <p className="text-sm font-bold text-primary">+3.2%</p>
                  <p className="text-xs text-muted-foreground">OTP</p>
                </div>
                <div>
                  <p className="text-sm font-bold text-primary">94%</p>
                  <p className="text-xs text-muted-foreground">Ready</p>
                </div>
                <div>
                  <p className="text-sm font-bold text-primary">2hr</p>
                  <p className="text-xs text-muted-foreground">Audit</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Unlike callout */}
      <div className="mt-6 max-w-4xl mx-auto">
        <div className="bg-card border border-primary/30 rounded-xl p-5">
          <p className="text-sm text-muted-foreground">
            <span className="font-semibold text-primary">Unlike</span> point solutions that manage safety, procedures, or training in isolation, 
            Comply365 connects all three into an intelligent operating system, turning signals into orchestrated change and audit-ready proof.
          </p>
        </div>
      </div>
    </SlideContainer>
  );
};

export default Slide2BeforeAfter;
