import SlideContainer from "./SlideContainer";
import { AlertCircle, CheckCircle2 } from "lucide-react";

const Slide2BeforeAfter = () => {
  const beforeItems = [
    "Safety, procedures, training are disconnected",
    "Investigations and changes happen manually",
    "Training not tied to operational signals",
    "Evidence assembled late and inconsistently",
  ];

  const afterItems = [
    "Detect → Trigger → Orchestrate → Prove",
    "Connected operating model",
    "Signals drive controlled execution",
    "Proof generated by default",
  ];

  return (
    <SlideContainer
      id="slide-2"
      title="Before & After"
      subtitle="Point Tools vs Connected Platform"
      slideNumber={2}
    >
      <div className="grid md:grid-cols-2 gap-6 lg:gap-10">
        {/* Before */}
        <div className="relative">
          <div className="relative bg-card border border-destructive/30 rounded-xl p-6 sm:p-8">
            <div className="flex items-center gap-3 mb-6">
              <div className="w-10 h-10 rounded-lg bg-destructive/20 flex items-center justify-center">
                <AlertCircle className="w-5 h-5 text-destructive" />
              </div>
              <div>
                <h3 className="text-xl font-bold text-destructive">Before</h3>
                <span className="text-xs text-muted-foreground">Fragmented Reality</span>
              </div>
            </div>

            {/* Disconnected circles visual */}
            <div className="relative h-40 mb-6">
              <svg viewBox="0 0 300 120" className="w-full h-full">
                {/* Broken connection lines */}
                <line x1="80" y1="60" x2="110" y2="60" stroke="hsl(var(--destructive))" strokeWidth="2" strokeDasharray="4 4" opacity="0.5" />
                <line x1="190" y1="60" x2="220" y2="60" stroke="hsl(var(--destructive))" strokeWidth="2" strokeDasharray="4 4" opacity="0.5" />
                
                {/* Safety circle */}
                <circle cx="55" cy="60" r="35" fill="none" stroke="hsl(var(--destructive))" strokeWidth="2" opacity="0.6" />
                <text x="55" y="60" textAnchor="middle" dominantBaseline="middle" fill="hsl(var(--destructive))" fontSize="10" fontWeight="600">Safety</text>
                
                {/* Procedures circle */}
                <circle cx="150" cy="60" r="35" fill="none" stroke="hsl(var(--destructive))" strokeWidth="2" opacity="0.6" />
                <text x="150" y="60" textAnchor="middle" dominantBaseline="middle" fill="hsl(var(--destructive))" fontSize="10" fontWeight="600">Procedures</text>
                
                {/* Training circle */}
                <circle cx="245" cy="60" r="35" fill="none" stroke="hsl(var(--destructive))" strokeWidth="2" opacity="0.6" />
                <text x="245" y="60" textAnchor="middle" dominantBaseline="middle" fill="hsl(var(--destructive))" fontSize="10" fontWeight="600">Training</text>
              </svg>
            </div>

            <ul className="space-y-3">
              {beforeItems.map((item, index) => (
                <li key={index} className="flex items-start gap-3 text-sm text-muted-foreground">
                  <span className="w-1.5 h-1.5 rounded-full bg-destructive mt-2 shrink-0" />
                  {item}
                </li>
              ))}
            </ul>

            <div className="mt-6 p-4 bg-destructive/10 rounded-lg border border-destructive/20">
              <p className="text-sm text-destructive font-medium">
                Result: High variability, repeat issues, slow recovery
              </p>
            </div>
          </div>
        </div>

        {/* After */}
        <div className="relative">
          <div className="relative bg-card border border-primary/30 rounded-xl p-6 sm:p-8">
            <div className="flex items-center gap-3 mb-6">
              <div className="w-10 h-10 rounded-lg bg-primary/20 flex items-center justify-center">
                <CheckCircle2 className="w-5 h-5 text-primary" />
              </div>
              <div>
                <h3 className="text-xl font-bold text-primary">After</h3>
                <span className="text-xs text-muted-foreground">Platform Operating Model</span>
              </div>
            </div>

            {/* Connected circles visual */}
            <div className="relative h-40 mb-6">
              <svg viewBox="0 0 300 120" className="w-full h-full">
                <defs>
                  <linearGradient id="connectionGrad" x1="0%" y1="0%" x2="100%" y2="0%">
                    <stop offset="0%" stopColor="hsl(var(--primary))" />
                    <stop offset="100%" stopColor="hsl(var(--accent))" />
                  </linearGradient>
                </defs>
                
                {/* Connection lines */}
                <path d="M 80 60 Q 115 35 150 60" fill="none" stroke="url(#connectionGrad)" strokeWidth="3" />
                <path d="M 150 60 Q 185 85 220 60" fill="none" stroke="url(#connectionGrad)" strokeWidth="3" />
                
                {/* Loop arrow */}
                <path d="M 245 45 Q 275 60 245 75 Q 200 95 150 95 Q 100 95 55 75 Q 25 60 55 45 Q 100 25 150 25 Q 200 25 245 45" 
                      fill="none" stroke="hsl(var(--primary))" strokeWidth="1.5" strokeDasharray="6 3" opacity="0.4" />
                
                {/* Safety circle */}
                <circle cx="55" cy="60" r="35" fill="hsl(var(--primary) / 0.1)" stroke="hsl(var(--primary))" strokeWidth="2" />
                <text x="55" y="60" textAnchor="middle" dominantBaseline="middle" fill="hsl(var(--primary))" fontSize="10" fontWeight="600">Safety</text>
                
                {/* Procedures circle */}
                <circle cx="150" cy="60" r="35" fill="hsl(var(--primary) / 0.1)" stroke="hsl(var(--primary))" strokeWidth="2" />
                <text x="150" y="60" textAnchor="middle" dominantBaseline="middle" fill="hsl(var(--primary))" fontSize="10" fontWeight="600">Procedures</text>
                
                {/* Training circle */}
                <circle cx="245" cy="60" r="35" fill="hsl(var(--primary) / 0.1)" stroke="hsl(var(--primary))" strokeWidth="2" />
                <text x="245" y="60" textAnchor="middle" dominantBaseline="middle" fill="hsl(var(--primary))" fontSize="10" fontWeight="600">Training</text>
              </svg>
            </div>

            <ul className="space-y-3">
              {afterItems.map((item, index) => (
                <li key={index} className="flex items-start gap-3 text-sm text-foreground">
                  <CheckCircle2 className="w-4 h-4 text-primary mt-0.5 shrink-0" />
                  {item}
                </li>
              ))}
            </ul>

            <div className="mt-6 p-4 bg-primary/10 rounded-lg border border-primary/20">
              <p className="text-sm text-primary font-medium">
                Result: Reduced variability, faster recovery, continuous proof
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* Unlike callout */}
      <div className="mt-8 max-w-4xl mx-auto">
        <div className="bg-card border border-primary/30 rounded-xl p-6">
          <p className="text-sm text-muted-foreground">
            <span className="font-semibold text-primary">Unlike</span> point solutions that manage safety, procedures, or training in isolation, 
            Comply365 unifies all three into one governed platform so operational signals trigger controlled change, 
            workforce readiness, and audit-ready proof by default.
          </p>
        </div>
      </div>
    </SlideContainer>
  );
};

export default Slide2BeforeAfter;
