import SalesSlideContainer from "@/components/sales-slides/SalesSlideContainer";
import { ArrowRight, Clock, CheckCircle2, Shield, TrendingUp } from "lucide-react";
import type { SlideNarrationProps } from "@/types/slideProps";

interface Exec2Slide2AfterProps extends SlideNarrationProps {
  slideNumber?: number;
}

const afterItems = [
  "Detect → Trigger → Orchestrate → Prove",
  "Connected operating model",
  "Signals drive controlled execution",
  "Proof generated by default",
];

const generateParticles = (count: number) => {
  const particles = [];
  for (let i = 0; i < count; i++) {
    const angle = (i / count) * Math.PI * 2;
    const radius = 8 + Math.random() * 5;
    const x = Math.cos(angle) * radius;
    const y = Math.sin(angle) * radius;
    particles.push({ x, y });
  }
  return particles;
};

const dtopSteps = [
  { label: "Detect", desc: "Surface signals from safety, content & training data" },
  { label: "Trigger", desc: "Automatically initiate the right response" },
  { label: "Orchestrate", desc: "Coordinate change across modules" },
  { label: "Prove", desc: "Generate audit-ready evidence of action" },
];

const outcomes = [
  { icon: TrendingUp, label: "OTP Improvement", value: "+3.2%", color: "text-emerald-400" },
  { icon: CheckCircle2, label: "Fleet Readiness", value: "94%", color: "text-blue-400" },
  { icon: Clock, label: "Audit Prep Time", value: "Months → 2hr", color: "text-amber-400" },
  { icon: Shield, label: "Repeat Events", value: "−40%", color: "text-purple-400" },
];

const Exec2Slide2After = ({
  slideNumber,
  isPlaying = false,
  isLoading = false,
  progress = 0,
  hasCompleted = false,
  onPlay,
  onPause,
  onNextSlide,
  onPrevSlide,
}: Exec2Slide2AfterProps) => {
  return (
    <SalesSlideContainer
      id="exec2-slide-2"
      title="The After: Operational Performance Platform"
      subtitle="A connected, intelligent, and predictive platform that turns signals into orchestrated change"
      slideNumber={slideNumber}
      variant="dark"
      isPlaying={isPlaying}
      isLoading={isLoading}
      progress={progress}
      hasCompleted={hasCompleted}
      onPlay={onPlay}
      onPause={onPause}
      onNextSlide={onNextSlide}
      onPrevSlide={onPrevSlide}
    >
      <div className="space-y-6">
        {/* Connected Visual + Category Definition */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-4 items-center">
          {/* Connected circles SVG */}
          <div className="relative h-40">
            <svg viewBox="0 0 300 140" className="w-full h-full">
              <defs>
                <linearGradient id="connectionGrad2" x1="0%" y1="0%" x2="100%" y2="0%">
                  <stop offset="0%" stopColor="hsl(var(--primary))" />
                  <stop offset="100%" stopColor="hsl(160 70% 45%)" />
                </linearGradient>
              </defs>

              {/* Connection paths */}
              <path d="M 80 50 Q 115 30 150 50" fill="none" stroke="url(#connectionGrad2)" strokeWidth="3" />
              <path d="M 150 50 Q 185 70 220 50" fill="none" stroke="url(#connectionGrad2)" strokeWidth="3" />

              {/* Unified loop */}
              <path d="M 245 35 Q 280 50 245 65 Q 200 85 150 85 Q 100 85 55 65 Q 20 50 55 35 Q 100 15 150 15 Q 200 15 245 35"
                    fill="none" stroke="hsl(var(--primary))" strokeWidth="1.5" opacity="0.3" />

              {/* Safety */}
              <g>
                <circle cx="55" cy="50" r="32" fill="hsl(var(--primary) / 0.15)" stroke="hsl(var(--primary))" strokeWidth="2" />
                {generateParticles(8).map((p, i) => (
                  <circle key={`as-${i}`} cx={55 + p.x} cy={50 + p.y} r="2.5" fill="hsl(var(--primary))" opacity="0.8" />
                ))}
                <text x="55" y="50" textAnchor="middle" dominantBaseline="middle" fill="hsl(var(--primary))" fontSize="9" fontWeight="600">Safety</text>
              </g>

              {/* Content */}
              <g>
                <circle cx="150" cy="50" r="32" fill="hsl(var(--primary) / 0.15)" stroke="hsl(var(--primary))" strokeWidth="2" />
                {generateParticles(10).map((p, i) => (
                  <circle key={`ap-${i}`} cx={150 + p.x} cy={50 + p.y} r="2.5" fill="hsl(var(--primary))" opacity="0.8" />
                ))}
                <text x="150" y="50" textAnchor="middle" dominantBaseline="middle" fill="hsl(var(--primary))" fontSize="9" fontWeight="600">Content</text>
              </g>

              {/* Training */}
              <g>
                <circle cx="245" cy="50" r="32" fill="hsl(var(--primary) / 0.15)" stroke="hsl(var(--primary))" strokeWidth="2" />
                {generateParticles(12).map((p, i) => (
                  <circle key={`at-${i}`} cx={245 + p.x} cy={50 + p.y} r="2.5" fill="hsl(var(--primary))" opacity="0.8" />
                ))}
                <text x="245" y="50" textAnchor="middle" dominantBaseline="middle" fill="hsl(var(--primary))" fontSize="9" fontWeight="600">Training</text>
              </g>

              {/* Connected badge */}
              <g transform="translate(150, 115)">
                <rect x="-45" y="-12" width="90" height="24" rx="4" fill="hsl(var(--primary) / 0.2)" stroke="hsl(var(--primary))" strokeWidth="1" />
                <text x="0" y="0" textAnchor="middle" dominantBaseline="middle" fill="hsl(var(--primary))" fontSize="9" fontWeight="600">65K+ Connected</text>
              </g>
            </svg>
          </div>

          {/* Category + bullets */}
          <div className="space-y-4">
            <div className="bg-primary/10 border border-primary/30 rounded-xl px-6 py-4 text-center">
              <p className="text-xs font-medium text-primary uppercase tracking-widest mb-1">Category We're Defining</p>
              <p className="text-xl font-bold text-foreground">Operational Performance Platform</p>
              <p className="text-sm text-muted-foreground mt-1">for Safety, Content & Training</p>
            </div>
            <ul className="space-y-2">
              {afterItems.map((item, index) => (
                <li key={index} className="flex items-start gap-3 text-sm text-foreground">
                  <CheckCircle2 className="w-4 h-4 text-primary mt-0.5 shrink-0" />
                  {item}
                </li>
              ))}
            </ul>
          </div>
        </div>

        {/* DTOP Pipeline */}
        <div>
          <p className="text-xs uppercase tracking-widest text-muted-foreground text-center mb-3">
            Continuous Improvement Operating Model
          </p>
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">
            {dtopSteps.map((step, i) => (
              <div key={step.label} className="relative">
                <div className="bg-card/60 border border-border/50 rounded-lg p-3 text-center h-full">
                  <div className="w-7 h-7 rounded-full bg-primary/20 text-primary font-bold text-xs flex items-center justify-center mx-auto mb-1.5">
                    {i + 1}
                  </div>
                  <p className="text-sm font-semibold text-foreground">{step.label}</p>
                  <p className="text-xs text-muted-foreground mt-1">{step.desc}</p>
                </div>
                {i < 3 && (
                  <ArrowRight className="hidden lg:block absolute -right-3 top-1/2 -translate-y-1/2 w-4 h-4 text-primary/50 z-10" />
                )}
              </div>
            ))}
          </div>
        </div>

        {/* Illustrative Outcomes */}
        <div>
          <p className="text-xs uppercase tracking-widest text-muted-foreground text-center mb-3">
            Illustrative Target Outcomes
          </p>
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">
            {outcomes.map((outcome) => (
              <div key={outcome.label} className="bg-card/40 border border-border/30 rounded-lg p-3 text-center">
                <outcome.icon className={`w-5 h-5 mx-auto mb-1.5 ${outcome.color}`} />
                <p className={`text-lg font-bold ${outcome.color}`}>{outcome.value}</p>
                <p className="text-xs text-muted-foreground mt-0.5">{outcome.label}</p>
              </div>
            ))}
          </div>
        </div>
      </div>
    </SalesSlideContainer>
  );
};

export default Exec2Slide2After;
