export interface SalesNarrationSlide {
  slideId: string;
  text: string;
}

export const salesDeckNarration: SalesNarrationSlide[] = [
  {
    slideId: "sales-slide-0",
    text: "What if operational performance was predictable? What if every signal was automatically tracked, trained, and proven? That's not a vision — that's what happens when you close the loop between safety, content, and training. Today, let me show you how.",
  },
  {
    slideId: "sales-slide-1",
    text: "Here's why most operations stay unpredictable. Foqua flags a hard landing trend on Monday. By Friday, safety has opened an investigation. Two weeks later, content gets notified via email. A month in, training is still waiting for scope. And when audit comes knocking? You're scrambling for evidence. Point tools can't close this loop because they were never designed to. Sound familiar?",
  },
  {
    slideId: "sales-slide-2",
    text: "The cost of fragmentation isn't abstract — it's measurable. Twelve thousand signals scattered across systems, with zero automated triggers. Eight thousand orphaned content items with no traceability. Three weeks average to investigate, while risks compound. And months of audit prep for every cycle. Regulators now expect connected evidence, not just compliance paperwork. Every week you wait, the gap widens.",
  },
  {
    slideId: "sales-slide-3",
    text: "The transformation from reactive to predictable is clear. Before: disconnected silos, manual handoffs, reactive responses, scattered evidence. After: a connected operating model where signals drive execution and proof is generated by default. The result? Predictable on-time performance, workforce readiness at ninety-four percent, and audit prep that takes hours instead of months.",
  },
  {
    slideId: "sales-slide-4",
    text: "Our platform follows a simple but powerful operating model: Detect, Trigger, Orchestrate, Prove. Detect surfaces signals from across your operation — Foqua, ASAP, audits, ops data. Trigger automatically initiates the right workflows. Orchestrate coordinates the response across training, content, and compliance. And Prove documents everything for audit-ready evidence. Signals become outcomes — by default.",
  },
  {
    slideId: "sales-slide-5",
    text: "Let me show you what this looks like in practice. Hard landing detection: Foqua flags a trend, the platform identifies affected pilots, targeted simulator training deploys within forty-eight hours. Result: seventy-eight percent reduction in repeat events within ninety days. Smoke and fumes detection: report clusters trigger root cause analysis, procedures update automatically, ground crews retrain immediately. Result: ninety-two percent reduction in reports. These aren't hypotheticals — they're real patterns our customers experience.",
  },
  {
    slideId: "sales-slide-6",
    text: "Every organization sits somewhere on the maturity curve. Most start at Stage One — fragmented and reactive. Best-in-class products can get you to Stage Two — managed compliance. But the real inflection point happens at Stage Three, when you connect safety, content, and training into a single platform. From there, you accelerate through intelligent and predictive operations. The traditional path takes five to seven years. With our platform, you can reach Stage Five in eighteen to twenty-four months.",
  },
  {
    slideId: "sales-slide-7",
    text: "Here's what predictable performance delivers. Schedule protection: hard landing trends detected early mean protected departures. Revenue protection: fatigue risks flagged proactively avoid costly cancellations. Cost savings: automated content updates eliminate rework cycles. Customer loyalty: compliance gaps closed immediately maintain trust. Close the loop. Predict the outcome.",
  },
  {
    slideId: "sales-slide-8",
    text: "Why Comply365? Three differentiators. First, a connected foundation — one version of truth across sixty-five thousand data points. Second, embedded intelligence — AI trained on over ten years of aviation operational data, not bolted on. Third, proof by default — every action logged, every change traced, always audit-ready. Point solutions manage silos. We close the loop.",
  },
  {
    slideId: "sales-slide-9",
    text: "Your operation has unique signals. Let's make them predictable. In a discovery session, we'll assess where you are on the maturity journey, identify your highest-impact opportunities, and build a custom ROI model for your operation. Detect, Trigger, Orchestrate, Prove — predictable performance starts now.",
  },
];

export const getSalesNarrationBySlideId = (slideId: string): string | undefined => {
  return salesDeckNarration.find((slide) => slide.slideId === slideId)?.text;
};
